version: "3"
services:
  db:
    container_name: pg_db
    hostname: database_pg
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "13432:5432"
    build: 
      context: .
      dockerfile: docker/pg/Dockerfile
    volumes:
      - ./data/pg/PostgreSql-Snippets/infile:/infile
      - ./data/pg/pg_data:/var/lib/postgresql/data
      - ./data/tempdb:/tempdb
      - ./data/temp:/temp



  mysql:
    image: mysql:5.7
    container_name: mysql_dev
    hostname: database_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '13306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql



  web:
    build: 
      context: .
      dockerfile: docker/web/Dockerfile
    image: web_apache
    volumes:
      - ./www/:/var/www/html/
      - ./data/attachments:/var/www/attachments
      - ./data/temp:/temp
    env_file:
      - ./env_web.env
    ports:
      - "80:80"
      - "85:85"
    links:
      - db
      - mysql
    depends_on:
      - db
      - mysql
    container_name: web_apache

#docker exec -it web_apache bash
